import type { Metadata } from "next";
import { Poppins, Neuton, Palanquin } from "next/font/google";
import "./globals.css";


const poppinsSans = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const neutonSerif = Neuton({
  variable: "--font-neuton",
  weight: ["200", "300", "400", "700", "800"], // Available weights for Neuton
  subsets: ["latin"],
});

const palanquinSans = Palanquin({
  variable: "--font-palanquin",
  weight: ["100", "200", "300", "400", "700"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable}  ${neutonSerif.variable} ${palanquinSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
